// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface InitResult {
    "config_dir": string;
    "runtime_root": string;
    "database_path": string;
    "initialized": boolean;
    "schema_healthy": boolean;
    "migrations_applied": number;
    "operation_recovery_cleanup_required": boolean;
}

export interface StatusResult {
    "config_dir": string;
    "runtime_root": string;
    "database_path": string;
    "initialized": boolean;
    "schema_healthy": boolean;
    "pending_operations": number;
    "failed_operations": number;
    "operation_recovery_cleanup_required": boolean;
}
