// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Profile {
    "id": string;
    "name": string;
    "description": string;
    "metadata": { [_ in string]?: any } | null;
    "created_at_unix_ms": number;
    "updated_at_unix_ms": number;
}
