// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../../internal/agent/models.js";

export function List(): $CancellablePromise<agent$0.State[] | null> {
    return $Call.ByID(172088100);
}

export function SetEnabled(id: string, enabled: boolean): $CancellablePromise<agent$0.State> {
    return $Call.ByID(2361277653, id, enabled);
}
