// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as antigravity$0 from "../../internal/antigravity/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateProfile(req: $models.CreateAntigravityProfileRequest): $CancellablePromise<antigravity$0.AntigravityProfileSaveResult> {
    return $Call.ByID(1779211844, req);
}

export function Detect(): $CancellablePromise<antigravity$0.AntigravityDetectResult> {
    return $Call.ByID(84501948);
}

export function ListProfiles(): $CancellablePromise<antigravity$0.AntigravityProfileListResult> {
    return $Call.ByID(945719165);
}

export function SaveCurrent(): $CancellablePromise<antigravity$0.AntigravityProfileSaveResult> {
    return $Call.ByID(1314540511);
}

export function ShowProfile(profileID: string): $CancellablePromise<antigravity$0.AntigravityProfileDetail> {
    return $Call.ByID(3573442403, profileID);
}

export function UpdateProfile(req: $models.UpdateAntigravityProfileRequest): $CancellablePromise<antigravity$0.AntigravityProfileDetail> {
    return $Call.ByID(3902032231, req);
}
