// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Dashboard(): $CancellablePromise<$models.DashboardResult> {
    return $Call.ByID(1685515930);
}

export function Environment(): $CancellablePromise<$models.Environment> {
    return $Call.ByID(3160996423);
}

export function Info(): $CancellablePromise<app$0.Info> {
    return $Call.ByID(929178434);
}

export function Initialize(): $CancellablePromise<app$0.InitResult> {
    return $Call.ByID(4207113600);
}
