// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appbackup$0 from "../../internal/appbackup/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../../internal/settings/models.js";

export function Create(): $CancellablePromise<appbackup$0.BackupDetail> {
    return $Call.ByID(1431869259);
}

export function Delete(req: appbackup$0.DeleteRequest): $CancellablePromise<void> {
    return $Call.ByID(3147389576, req);
}

export function Export(req: appbackup$0.ExportRequest): $CancellablePromise<appbackup$0.ExportResult> {
    return $Call.ByID(254880049, req);
}

export function ExportKey(req: appbackup$0.ExportKeyRequest): $CancellablePromise<appbackup$0.ExportKeyResult> {
    return $Call.ByID(149505944, req);
}

export function ImportKey(req: appbackup$0.ImportKeyRequest): $CancellablePromise<appbackup$0.ImportKeyResult> {
    return $Call.ByID(2292850313, req);
}

export function KeyStatus(): $CancellablePromise<appbackup$0.KeyStatus> {
    return $Call.ByID(930451084);
}

export function List(): $CancellablePromise<appbackup$0.ListResult> {
    return $Call.ByID(3687121795);
}

export function PreviewRestore(source: appbackup$0.RestoreSource): $CancellablePromise<appbackup$0.RestorePreview> {
    return $Call.ByID(3790909753, source);
}

export function Restore(req: appbackup$0.RestoreRequest): $CancellablePromise<appbackup$0.RestoreResult> {
    return $Call.ByID(710991883, req);
}

export function SetAutomatic(enabled: boolean): $CancellablePromise<settings$0.Desktop> {
    return $Call.ByID(249244440, enabled);
}

export function Show(backupID: string): $CancellablePromise<appbackup$0.BackupDetail> {
    return $Call.ByID(3701096046, backupID);
}
