// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateProfile(req: $models.CreateCodexProfileRequest): $CancellablePromise<app$0.CodexProfileSaveResult> {
    return $Call.ByID(2556578151, req);
}

export function Detect(): $CancellablePromise<app$0.CodexDetectResult> {
    return $Call.ByID(1422541865);
}

export function ForkProfile(req: $models.ForkCodexProfileRequest): $CancellablePromise<app$0.CodexProfileSaveResult> {
    return $Call.ByID(2400690215, req);
}

export function ListProfiles(): $CancellablePromise<app$0.CodexProfileListResult> {
    return $Call.ByID(2936238732);
}

export function ShowProfile(profileID: string): $CancellablePromise<app$0.CodexProfileDetail> {
    return $Call.ByID(1381065948, profileID);
}

export function SyncProfile(req: $models.SyncCodexProfileRequest): $CancellablePromise<app$0.CodexProfileSaveResult> {
    return $Call.ByID(3826250294, req);
}

export function UpdateProfileMetadata(req: $models.UpdateCodexProfileMetadataRequest): $CancellablePromise<app$0.Profile> {
    return $Call.ByID(1493912893, req);
}
