// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyProfileImport(req: $models.ApplyCodexProfileImportRequest): $CancellablePromise<app$0.CodexProfileImportResult> {
    return $Call.ByID(1095961474, req);
}

export function CopyConfigSet(req: $models.CopyCodexConfigSetRequest): $CancellablePromise<app$0.CodexConfigSet> {
    return $Call.ByID(359109991, req);
}

export function CreateConfigSet(req: $models.CreateCodexConfigSetRequest): $CancellablePromise<app$0.CodexConfigSet> {
    return $Call.ByID(2586023468, req);
}

export function CreateProfile(req: $models.CreateCodexProfileRequest): $CancellablePromise<app$0.CodexProfileSaveResult> {
    return $Call.ByID(2556578151, req);
}

export function DeleteConfigSet(configSetID: string): $CancellablePromise<void> {
    return $Call.ByID(2847067097, configSetID);
}

export function Detect(): $CancellablePromise<app$0.CodexDetectResult> {
    return $Call.ByID(1422541865);
}

export function ExportProfiles(req: $models.ExportCodexProfilesRequest): $CancellablePromise<app$0.CodexProfileExportResult> {
    return $Call.ByID(2603279926, req);
}

export function ForkProfile(req: $models.ForkCodexProfileRequest): $CancellablePromise<app$0.CodexProfileSaveResult> {
    return $Call.ByID(2400690215, req);
}

export function InspectProfileImport(inputPath: string): $CancellablePromise<app$0.CodexProfileImportPlan> {
    return $Call.ByID(3289700062, inputPath);
}

export function ListConfigSets(): $CancellablePromise<app$0.CodexConfigSetListResult> {
    return $Call.ByID(2706686941);
}

export function ListProfiles(): $CancellablePromise<app$0.CodexProfileListResult> {
    return $Call.ByID(2936238732);
}

export function SaveActiveProfileState(): $CancellablePromise<app$0.CodexProfileStateSaveResult> {
    return $Call.ByID(2732837523);
}

export function SetProfileConfig(req: $models.UpdateCodexProfileConfigSetRequest): $CancellablePromise<app$0.CodexProfileDetail> {
    return $Call.ByID(7103721, req);
}

export function ShowConfigSet(configSetID: string): $CancellablePromise<app$0.CodexConfigSet> {
    return $Call.ByID(4233188119, configSetID);
}

export function ShowProfile(profileID: string): $CancellablePromise<app$0.CodexProfileDetail> {
    return $Call.ByID(1381065948, profileID);
}

export function UpdateConfigSet(req: $models.UpdateCodexConfigSetRequest): $CancellablePromise<app$0.CodexConfigSet> {
    return $Call.ByID(1065701395, req);
}

export function UpdateProfileMetadata(req: $models.UpdateCodexProfileMetadataRequest): $CancellablePromise<app$0.Profile> {
    return $Call.ByID(1493912893, req);
}
