// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as doctor$0 from "../../internal/doctor/models.js";

export function RepairLock(confirm: boolean): $CancellablePromise<doctor$0.DoctorRepairLockResult> {
    return $Call.ByID(19841452, confirm);
}

export function Run(): $CancellablePromise<doctor$0.DoctorResult> {
    return $Call.ByID(3471832615);
}
