// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as grokbuild$0 from "../../internal/grokbuild/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profile$0 from "../../internal/profile/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CopyConfigSet(req: $models.CopyGrokBuildConfigSetRequest): $CancellablePromise<grokbuild$0.ConfigSet> {
    return $Call.ByID(639878353, req);
}

export function CreateConfigSet(req: $models.CreateGrokBuildConfigSetRequest): $CancellablePromise<grokbuild$0.ConfigSet> {
    return $Call.ByID(474817358, req);
}

export function CreateProfile(req: $models.CreateGrokBuildProfileRequest): $CancellablePromise<grokbuild$0.ProfileSaveResult> {
    return $Call.ByID(208301309, req);
}

export function DeleteConfigSet(configSetID: string): $CancellablePromise<void> {
    return $Call.ByID(795731395, configSetID);
}

export function Detect(): $CancellablePromise<grokbuild$0.DetectResult> {
    return $Call.ByID(1920359267);
}

export function ForkProfile(req: $models.ForkGrokBuildProfileRequest): $CancellablePromise<grokbuild$0.ProfileSaveResult> {
    return $Call.ByID(84190781, req);
}

export function GetSettings(): $CancellablePromise<grokbuild$0.Settings> {
    return $Call.ByID(3051965125);
}

export function ListConfigSets(): $CancellablePromise<grokbuild$0.ConfigSetListResult> {
    return $Call.ByID(2533374179);
}

export function ListProfiles(): $CancellablePromise<grokbuild$0.ProfileListResult> {
    return $Call.ByID(2538035414);
}

export function ReadProfileQuota(profileID: string): $CancellablePromise<grokbuild$0.GrokBuildProfileQuota> {
    return $Call.ByID(1290892715, profileID);
}

export function SaveActiveProfileState(expectedProfileID: string): $CancellablePromise<grokbuild$0.ProfileStateSaveResult> {
    return $Call.ByID(1134372713, expectedProfileID);
}

export function SetProfileConfig(req: $models.UpdateGrokBuildProfileConfigSetRequest): $CancellablePromise<grokbuild$0.ProfileDetail> {
    return $Call.ByID(2779879795, req);
}

export function ShowConfigSet(configSetID: string): $CancellablePromise<grokbuild$0.ConfigSet> {
    return $Call.ByID(3333173309, configSetID);
}

export function ShowProfile(profileID: string): $CancellablePromise<grokbuild$0.ProfileDetail> {
    return $Call.ByID(1243514542, profileID);
}

export function UpdateConfigSet(req: $models.UpdateGrokBuildConfigSetRequest): $CancellablePromise<grokbuild$0.ConfigSet> {
    return $Call.ByID(2716336517, req);
}

export function UpdateProfileMetadata(req: $models.UpdateGrokBuildProfileMetadataRequest): $CancellablePromise<profile$0.Profile> {
    return $Call.ByID(2613071443, req);
}

export function UpdateSettings(req: grokbuild$0.UpdateSettingsRequest): $CancellablePromise<grokbuild$0.Settings> {
    return $Call.ByID(1525180976, req);
}
