// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";

export interface CodexProfileCaptureRequest {
    "profile_id": string;
    "account_id": string;
    "name"?: string | null;
    "description"?: string | null;
}

export interface CodexProfileSetRequest {
    "profile_id": string;
    "model": string;
    "model_provider": string;
    "openai_base_url"?: string | null;
    "account_id": string;
    "name"?: string | null;
    "description"?: string | null;
}

export interface DashboardResult {
    "info": app$0.Info;
    "environment": Environment;
    "status": app$0.StatusResult;
    "doctor"?: app$0.DoctorResult | null;
    "providers": app$0.Provider[] | null;
    "profiles": app$0.Profile[] | null;
    "active_states": app$0.ActiveProviderState[] | null;
    "usage"?: app$0.UsageSummaryResult | null;
    "startup_error"?: DesktopError | null;
    "generated_at_unix_ms": number;
}

export interface DesktopError {
    "code": string;
    "message": string;
    "details"?: { [_ in string]?: any } | null;
}

export interface Environment {
    "config_dir": string;
    "codex_dir": string;
}

export interface SwitchApplyRequest {
    "provider_id": string;
    "profile_id": string;
    "expected_plan_fingerprint": string;
    "confirm": boolean;
}
