// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";

export interface ApplyCodexProfileImportRequest {
    "input_path": string;
    "expected_plan_fingerprint": string;
    "confirm": boolean;
}

export interface CodexProfileQuotaRuntimeStatus {
    "profile_id": string;
    "running": boolean;
    "last_task"?: string;
    "last_started_at_unix_ms": number;
    "last_completed_at_unix_ms": number;
    "last_success_at_unix_ms": number;
    "next_run_at_unix_ms": number;
    "status": app$0.CodexProfileQuotaStatus;
    "snapshot"?: app$0.CodexQuotaSnapshot | null;
    "error_code"?: string;
}

export interface CodexQuotaRuntimeStatus {
    "app_server_status": string;
    "profiles": CodexProfileQuotaRuntimeStatus[] | null;
}

export interface CopyCodexConfigSetRequest {
    "source_config_set_id": string;
    "config_set_id": string;
    "name": string;
    "description"?: string;
}

export interface CreateAntigravityProfileRequest {
    "profile_id": string;
    "name"?: string | null;
    "description"?: string | null;
}

export interface CreateClaudeCodeProfileRequest {
    "profile_id": string;
    "name"?: string | null;
    "description"?: string | null;
}

export interface CreateCodexConfigSetRequest {
    "config_set_id": string;
    "name": string;
    "description"?: string;
}

export interface CreateCodexProfileRequest {
    "profile_id": string;
    "name"?: string | null;
    "description"?: string | null;
    "new_config_set_id"?: string;
    "new_config_set_name"?: string | null;
    "new_config_set_description"?: string | null;
}

export interface DashboardResult {
    "info": app$0.Info;
    "environment": Environment;
    "status": app$0.StatusResult;
    "doctor"?: app$0.DoctorResult | null;
    "providers": app$0.Provider[] | null;
    "profiles": app$0.Profile[] | null;
    "active_states": app$0.ActiveProviderState[] | null;
    "codex_profiles"?: app$0.CodexProfileListResult | null;
    "codex_config_sets"?: app$0.CodexConfigSetListResult | null;
    "antigravity_profiles"?: app$0.AntigravityProfileListResult | null;
    "claude_code_profiles"?: app$0.ClaudeCodeProfileListResult | null;
    "usage"?: app$0.UsageSummaryResult | null;
    "startup_error"?: DesktopError | null;
    "generated_at_unix_ms": number;
}

export interface DesktopError {
    "code": string;
    "message": string;
    "details"?: { [_ in string]?: any } | null;
}

export interface Environment {
    "config_dir": string;
    "codex_dir": string;
}

export interface ExportCodexProfilesRequest {
    "profile_ids"?: string[] | null;
    "output_path": string;
    "overwrite": boolean;
}

export interface ForkCodexProfileRequest {
    "source_profile_id": string;
    "profile_id": string;
    "credential_binding": string;
    "config_binding": string;
    "new_config_set_id"?: string;
    "new_config_set_name"?: string | null;
    "new_config_set_description"?: string | null;
    "name"?: string | null;
    "description"?: string | null;
}

export interface SwitchApplyRequest {
    "provider_id": string;
    "profile_id": string;
    "expected_plan_fingerprint": string;
    "confirm": boolean;
}

export interface UpdateAntigravityProfileRequest {
    "profile_id": string;
    "name"?: string | null;
    "description"?: string | null;
}

export interface UpdateClaudeCodeProfileRequest {
    "profile_id": string;
    "name"?: string | null;
    "description"?: string | null;
}

export interface UpdateCodexConfigSetRequest {
    "config_set_id": string;
    "name"?: string | null;
    "description"?: string | null;
}

export interface UpdateCodexProfileConfigSetRequest {
    "profile_id": string;
    "config_set_id": string;
}

export interface UpdateCodexProfileMetadataRequest {
    "profile_id": string;
    "name"?: string | null;
    "description"?: string | null;
}

export interface UsageAutoSyncError {
    "code": string;
    "message": string;
}

export interface UsageAutoSyncStatus {
    "interval_seconds": number;
    "syncing": boolean;
    "outcome": string;
    "last_started_at_unix_ms": number;
    "last_completed_at_unix_ms": number;
    "last_success_at_unix_ms": number;
    "import_error_count": number;
    "error"?: UsageAutoSyncError | null;
}
