// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profile$0 from "../../internal/profile/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profiletarget$0 from "../../internal/profiletarget/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "../../internal/provider/models.js";

export function ListProfiles(): $CancellablePromise<profile$0.Profile[] | null> {
    return $Call.ByID(2779719102);
}

export function ListProviders(): $CancellablePromise<provider$0.Provider[] | null> {
    return $Call.ByID(2942677598);
}

export function ListTargets(profileID: string, providerID: string): $CancellablePromise<profiletarget$0.ProfileTarget[] | null> {
    return $Call.ByID(1610672050, profileID, providerID);
}
