// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";

export function ListProfiles(): $CancellablePromise<app$0.Profile[] | null> {
    return $Call.ByID(2779719102);
}

export function ListProviders(): $CancellablePromise<app$0.Provider[] | null> {
    return $Call.ByID(2942677598);
}

export function ListTargets(profileID: string, providerID: string): $CancellablePromise<app$0.ProfileTarget[] | null> {
    return $Call.ByID(1610672050, profileID, providerID);
}
