// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../../internal/settings/models.js";

export function Get(): $CancellablePromise<settings$0.Desktop> {
    return $Call.ByID(1068180696);
}

export function Update(req: settings$0.UpdateRequest): $CancellablePromise<settings$0.Desktop> {
    return $Call.ByID(340284781, req);
}
