// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";

export function Get(): $CancellablePromise<app$0.DesktopSettings> {
    return $Call.ByID(1068180696);
}

export function Update(req: app$0.UpdateDesktopSettingsRequest): $CancellablePromise<app$0.DesktopSettings> {
    return $Call.ByID(340284781, req);
}
