// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Apply(req: $models.SwitchApplyRequest): $CancellablePromise<app$0.ApplySwitchResult> {
    return $Call.ByID(1472033683, req);
}

export function BuildPlan(providerID: string, profileID: string): $CancellablePromise<app$0.SwitchPlan> {
    return $Call.ByID(3697045652, providerID, profileID);
}
