// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as usage$0 from "../../internal/usage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AutoSyncStatus(): $CancellablePromise<$models.UsageAutoSyncStatus> {
    return $Call.ByID(2973972616);
}

export function Report(providerID: string, rangeValue: string): $CancellablePromise<usage$0.UsageReportResult> {
    return $Call.ByID(2463093428, providerID, rangeValue);
}

export function Summary(providerID: string): $CancellablePromise<usage$0.UsageSummaryResult> {
    return $Call.ByID(2239958706, providerID);
}
