// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";

export function Summary(providerID: string): $CancellablePromise<app$0.UsageSummaryResult> {
    return $Call.ByID(2239958706, providerID);
}

export function SyncCodex(): $CancellablePromise<app$0.UsageSyncResult> {
    return $Call.ByID(3772230292);
}
