// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profile$0 from "../profile/models.js";

export interface AntigravityDetectResult {
    "provider_id": string;
    "adapter_id": string;
    "credential_status": string;
    "profiledeck_initialized": boolean;
    "provider_exists": boolean;
    "provider_compatible": boolean;
    "warnings": string[] | null;
}

export interface AntigravityProfileDetail {
    "summary": AntigravityProfileSummary;
}

export interface AntigravityProfileListResult {
    "profiles": AntigravityProfileSummary[] | null;
}

export interface AntigravityProfileQuota {
    "profile_id": string;
    "credential_id": string;
    "status": AntigravityProfileQuotaStatus;
    "snapshot"?: AntigravityQuotaSnapshot | null;
}

export enum AntigravityProfileQuotaStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AntigravityProfileQuotaAvailable = "available",
    AntigravityProfileQuotaInactive = "inactive",
    AntigravityProfileQuotaAuthRequired = "auth_required",
    AntigravityProfileQuotaUnavailable = "unavailable",
};

export interface AntigravityProfileSaveResult {
    "operation_id": string;
    "summary": AntigravityProfileSummary;
    "warnings": string[] | null;
}

export interface AntigravityProfileSummary {
    "profile": profile$0.Profile;
    "provider_id": string;
    "credential_id": string;
    "credential_reference_count": number;
    "expires_at_unix_ms"?: number;
    "active": boolean;
    "active_operation_id"?: string;
    "updated_at_unix_ms": number;
    "warnings"?: string[] | null;
}

export interface AntigravityQuotaBucket {
    "bucket_id": string;
    "window": string;
    "remaining_percent": number;
    "reset_at_unix_seconds": number;
}

export interface AntigravityQuotaGroup {
    "display_name": string;
    "buckets": AntigravityQuotaBucket[] | null;
}

export interface AntigravityQuotaSnapshot {
    "fetched_at_unix_ms": number;
    "groups": AntigravityQuotaGroup[] | null;
}
