// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum ID {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Codex = "codex",
    Antigravity = "antigravity",
    ClaudeCode = "claude-code",
    GrokBuild = "grok-build",
};

export interface Manifest {
    "id": ID;
    "display_name": string;
    "provider_ids": string[] | null;
    "default_desktop_enabled": boolean;
}

export interface State {
    "manifest": Manifest;
    "enabled": boolean;
}
