// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    ApplyRollbackResult,
    ApplySwitchResult,
    BackupDetail,
    BackupEntrySummary,
    BackupSummary,
    ListBackupsResult,
    PlanBinding,
    PlanOperation,
    PlanProfile,
    PlanProvider,
    RecoverFailedSwitchResult,
    RollbackCounts,
    StateCapture,
    SwitchCounts,
    SwitchPlan,
    TextPreview
} from "./models.js";
