// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ApplySwitchResult {
    "operation_id": string;
    "status": string;
    "provider": PlanProvider;
    "profile": PlanProfile;
    "plan_fingerprint": string;
    "counts": SwitchCounts;
    "recovery_cleanup_completed": boolean;
    "warnings": string[] | null;
}

export interface PlanBinding {
    "target_id": string;
    "current_resource_id"?: string;
    "target_resource_id": string;
    "changed": boolean;
}

export interface PlanOperation {
    "provider_id": string;
    "profile_id": string;
    "target_id": string;
    "backend_id": string;
    "target_label": string;
    "path": string;
    "format": string;
    "strategy": string;
    "action": string;
    "status_reason": string;
    "file_exists": boolean;
    "is_symlink": boolean;
    "before_sha256": string;
    "desired_sha256": string;
    "before_preview": TextPreview;
    "desired_preview": TextPreview;
    "after_preview": TextPreview;
    "warnings": string[] | null;
}

export interface PlanProfile {
    "id": string;
    "name": string;
    "description": string;
}

export interface PlanProvider {
    "id": string;
    "name": string;
    "adapter_id": string;
}

export interface RecoverOperationResult {
    "source_operation_id": string;
    "recovery_operation_id"?: string;
    "action": string;
    "status": string;
    "provider_id"?: string;
    "profile_id"?: string;
    "restored_profile_id"?: string;
    "counts": RecoveryCounts;
    "recovery_cleanup_completed": boolean;
}

export interface RecoveryCounts {
    "restore": number;
    "remove": number;
    "noop": number;
}

export interface RecoveryInspection {
    "operation_id": string;
    "status": string;
    "action"?: string;
    "reason": string;
}

export interface StateCapture {
    "resource_kind": string;
    "resource_id": string;
    "resource_name"?: string;
    "stored_sha256": string;
    "current_sha256": string;
    "changed"?: boolean;
}

export interface SwitchCounts {
    "create": number;
    "update": number;
    "noop": number;
}

export interface SwitchPlan {
    "created_at_unix_ms": number;
    "read_only": boolean;
    "plan_fingerprint": string;
    "provider": PlanProvider;
    "profile": PlanProfile;
    "bindings"?: PlanBinding[] | null;
    "state_captures"?: StateCapture[] | null;
    "operations": PlanOperation[] | null;
    "warnings": string[] | null;
}

export interface TextPreview {
    "content": string;
    "truncated": boolean;
}
