// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface BackupDetail {
    "id": string;
    "kind": string;
    "created_at_unix_ms": number;
    "size_bytes": number;
    "reason": string;
    "format_version": number;
}

export interface BackupSummary {
    "id": string;
    "kind": string;
    "created_at_unix_ms": number;
    "size_bytes": number;
}

export interface DeleteRequest {
    "backup_id": string;
    "confirm": boolean;
}

export interface ExportKeyRequest {
    "output_path": string;
    "confirm": boolean;
}

export interface ExportKeyResult {
    "path": string;
    "recipient": string;
}

export interface ExportRequest {
    "backup_id": string;
    "output_path": string;
    "overwrite": boolean;
}

export interface ExportResult {
    "backup": BackupSummary;
    "path": string;
}

export interface ImportKeyRequest {
    "input_path": string;
    "replace": boolean;
    "confirm": boolean;
}

export interface ImportKeyResult {
    "recipient": string;
    "changed": boolean;
}

export interface KeyStatus {
    "available": boolean;
    "recipient"?: string;
}

export interface ListResult {
    "backups": BackupSummary[] | null;
    "automatic_cleanup_required": boolean;
}

export interface RestorePreview {
    "backup": BackupDetail;
    "fingerprint": string;
    "current_database_healthy": boolean;
    "schema_upgrade_required": boolean;
}

export interface RestoreRequest {
    "source": RestoreSource;
    "expected_fingerprint": string;
    "confirm": boolean;
}

export interface RestoreResult {
    "backup": BackupDetail;
    "safety_backup"?: BackupSummary | null;
    "safety_backup_skipped": boolean;
    "recovery_cleanup_completed": boolean;
    "restart_required": boolean;
}

export interface RestoreSource {
    "backup_id"?: string;
    "file_path"?: string;
}
