// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ActiveProviderState {
    "provider_id": string;
    "provider_name": string;
    "profile_id": string;
    "profile_name": string;
    "operation_id": string;
    "updated_at_unix_ms": number;
    "profile_available": boolean;
}

export interface ApplyRollbackResult {
    "operation_id": string;
    "status": string;
    "source_operation_id": string;
    "provider_id": string;
    "profile_id": string;
    "restored_profile_id": string;
    "counts": RollbackCounts;
    "backup_path": string;
    "warnings": string[] | null;
}

export interface ApplySwitchResult {
    "operation_id": string;
    "status": string;
    "provider": PlanProvider;
    "profile": PlanProfile;
    "plan_fingerprint": string;
    "counts": SwitchCounts;
    "backup_path": string;
    "warnings": string[] | null;
}

export interface BackupDetail {
    "backup_id": string;
    "path": string;
    "operation_id": string;
    "operation_type": string;
    "operation_status": string;
    "provider_id": string;
    "profile_id": string;
    "plan_fingerprint": string;
    "created_at_unix_ms": number;
    "entry_count": number;
    "valid": boolean;
    "invalid_reason"?: string;
    "rollback_supported": boolean;
    "unsupported_reason"?: string;
    "entries": BackupEntrySummary[] | null;
}

export interface BackupEntrySummary {
    "target_id": string;
    "path": string;
    "action": string;
    "existed": boolean;
    "before_sha256": string;
    "mode"?: string;
}

export interface BackupSummary {
    "backup_id": string;
    "path": string;
    "operation_id": string;
    "operation_type": string;
    "operation_status": string;
    "provider_id": string;
    "profile_id": string;
    "plan_fingerprint": string;
    "created_at_unix_ms": number;
    "entry_count": number;
    "valid": boolean;
    "invalid_reason"?: string;
    "rollback_supported": boolean;
    "unsupported_reason"?: string;
}

export interface CodexConfigSet {
    "id": string;
    "name": string;
    "description"?: string;
    "reference_count": number;
    "active": boolean;
    "model"?: string;
    "model_provider"?: string;
    "openai_base_url"?: string;
    "payload_sha256": string;
    "created_at_unix_ms": number;
    "updated_at_unix_ms": number;
}

export interface CodexConfigSetListResult {
    "config_sets": CodexConfigSet[] | null;
}

export interface CodexDetectResult {
    "provider_id": string;
    "adapter_id": string;
    "codex_dir": string;
    "config_path": string;
    "auth_path": string;
    "codex_dir_exists": boolean;
    "config_status": string;
    "auth_status": string;
    "profiledeck_initialized": boolean;
    "provider_exists": boolean;
    "provider_adapter_id": string;
    "provider_compatible": boolean;
    "warnings": string[] | null;
}

export interface CodexLoginStateSummary {
    "credential_id": string;
    "codex_account_id"?: string;
    "reference_count": number;
    "updated_at_unix_ms": number;
}

export interface CodexProfileDetail {
    "summary": CodexProfileSummary;
    "login"?: CodexLoginStateSummary | null;
    "config_set"?: CodexConfigSet | null;
}

export interface CodexProfileExportResult {
    "path": string;
    "sha256": string;
    "file_mode": string;
    "profile_count": number;
    "credential_count": number;
    "config_set_count": number;
    "warnings": string[] | null;
}

export interface CodexProfileImportCounts {
    "create": number;
    "unchanged": number;
    "conflict": number;
}

export interface CodexProfileImportItem {
    "kind": string;
    "id": string;
    "name"?: string;
    "credential_id"?: string;
    "config_set_id"?: string;
    "action": string;
    "reason"?: string;
}

export interface CodexProfileImportPlan {
    "path": string;
    "file_sha256": string;
    "plan_fingerprint": string;
    "codex_dir": string;
    "can_apply": boolean;
    "no_changes": boolean;
    "counts": CodexProfileImportCounts;
    "items": CodexProfileImportItem[] | null;
    "profile_count": number;
    "credential_count": number;
    "config_set_count": number;
    "warnings": string[] | null;
}

export interface CodexProfileImportResult {
    "operation_id"?: string;
    "file_sha256": string;
    "plan_fingerprint": string;
    "changed": boolean;
    "counts": CodexProfileImportCounts;
    "profile_count": number;
    "credential_count": number;
    "config_set_count": number;
    "warnings": string[] | null;
}

export interface CodexProfileListResult {
    "profiles": CodexProfileSummary[] | null;
}

export interface CodexProfileSaveResult {
    "operation_id": string;
    "provider": Provider;
    "profile": Profile;
    "summary": CodexProfileSummary;
    "config_set": CodexConfigSet;
    "codex_dir": string;
    "config_path": string;
    "auth_path": string;
    "warnings"?: string[] | null;
}

export interface CodexProfileStateSaveResult {
    "operation_id": string;
    "profile_id": string;
    "credential_id": string;
    "credential_reference_count": number;
    "config_set": CodexConfigSet;
    "warnings"?: string[] | null;
}

export interface CodexProfileSummary {
    "profile": Profile;
    "provider_id": string;
    "credential_id"?: string;
    "credential_reference_count": number;
    "codex_account_id"?: string;
    "config_set_id"?: string;
    "config_set_name"?: string;
    "config_set_reference_count": number;
    "model"?: string;
    "model_provider"?: string;
    "openai_base_url"?: string;
    "active": boolean;
    "active_operation_id"?: string;
    "updated_at_unix_ms": number;
    "warnings"?: string[] | null;
}

export interface DesktopSettings {
    "language": string;
    "usage_sync_interval_seconds": number;
}

export interface DoctorFinding {
    "id": string;
    "level": string;
    "message": string;
    "details"?: { [_ in string]?: any } | null;
}

export interface DoctorLock {
    "path": string;
    "exists": boolean;
    "owner"?: string;
    "operation_id"?: string;
    "pid"?: number;
    "pid_state": string;
    "created_at_unix_ms"?: number;
    "operation_status"?: string;
    "os_lock_state": string;
    "stale_candidate": boolean;
    "repairable": boolean;
    "level": string;
    "reason": string;
}

export interface DoctorOperation {
    "id": string;
    "operation_type": string;
    "status": string;
    "checkpoint"?: string;
    "provider_id"?: string;
    "profile_id"?: string;
    "backup_path"?: string;
    "backup_id"?: string;
    "source_operation_id"?: string;
    "rollback_kind"?: string;
    "recovery_status"?: string;
    "recovery_reason"?: string;
    "error_code"?: string;
    "error_message"?: string;
    "updated_at_unix_ms": number;
    "level": string;
    "reason": string;
}

export interface DoctorRepairLockResult {
    "path": string;
    "repaired": boolean;
    "reason": string;
}

export interface DoctorResult {
    "config_dir": string;
    "runtime_root": string;
    "database_path": string;
    "overall_level": string;
    "findings": DoctorFinding[] | null;
    "operations": DoctorOperation[] | null;
    "lock": DoctorLock;
}

export interface Info {
    "ProductName": string;
    "CLIName": string;
    "Version": string;
    "Commit": string;
    "BuildDate": string;
}

export interface InitResult {
    "config_dir": string;
    "runtime_root": string;
    "database_path": string;
    "initialized": boolean;
    "schema_healthy": boolean;
    "migrations_applied": number;
}

export interface ListBackupsResult {
    "backups": BackupSummary[] | null;
}

export interface PlanBinding {
    "target_id": string;
    "current_resource_id"?: string;
    "target_resource_id": string;
    "changed": boolean;
}

export interface PlanOperation {
    "provider_id": string;
    "profile_id": string;
    "target_id": string;
    "path": string;
    "format": string;
    "strategy": string;
    "action": string;
    "status_reason": string;
    "file_exists": boolean;
    "is_symlink": boolean;
    "before_sha256": string;
    "desired_sha256": string;
    "before_preview": TextPreview;
    "desired_preview": TextPreview;
    "after_preview": TextPreview;
    "warnings": string[] | null;
}

export interface PlanProfile {
    "id": string;
    "name": string;
    "description": string;
}

export interface PlanProvider {
    "id": string;
    "name": string;
    "adapter_id": string;
}

export interface Profile {
    "id": string;
    "name": string;
    "description": string;
    "metadata": { [_ in string]?: any } | null;
    "created_at_unix_ms": number;
    "updated_at_unix_ms": number;
}

export interface ProfileTarget {
    "profile_id": string;
    "provider_id": string;
    "target_id": string;
    "path": string;
    "format": string;
    "strategy": string;
    "enabled": boolean;
    "value_preview": TextPreview;
    "metadata": { [_ in string]?: any } | null;
    "created_at_unix_ms": number;
    "updated_at_unix_ms": number;
}

export interface Provider {
    "id": string;
    "name": string;
    "adapter_id": string;
    "enabled": boolean;
    "metadata": { [_ in string]?: any } | null;
    "created_at_unix_ms": number;
    "updated_at_unix_ms": number;
}

export interface RecoverFailedSwitchResult {
    "operation_id": string;
    "operation_type": string;
    "rollback_kind": string;
    "status": string;
    "source_operation_id": string;
    "provider_id": string;
    "profile_id": string;
    "restored_profile_id": string;
    "counts": RollbackCounts;
    "backup_path": string;
    "warnings": string[] | null;
}

export interface RollbackCounts {
    "restore": number;
    "remove": number;
    "noop": number;
}

export interface StateCapture {
    "resource_kind": string;
    "resource_id": string;
    "resource_name"?: string;
    "stored_sha256": string;
    "current_sha256": string;
}

export interface StatusResult {
    "config_dir": string;
    "runtime_root": string;
    "database_path": string;
    "initialized": boolean;
    "schema_healthy": boolean;
    "pending_operations": number;
    "failed_operations": number;
}

export interface SwitchCounts {
    "create": number;
    "update": number;
    "noop": number;
}

export interface SwitchPlan {
    "created_at_unix_ms": number;
    "read_only": boolean;
    "plan_fingerprint": string;
    "provider": PlanProvider;
    "profile": PlanProfile;
    "bindings"?: PlanBinding[] | null;
    "state_captures"?: StateCapture[] | null;
    "operations": PlanOperation[] | null;
    "warnings": string[] | null;
}

export interface TextPreview {
    "content": string;
    "truncated": boolean;
}

export interface UpdateDesktopSettingsRequest {
    "config_dir": string;
    "language"?: string | null;
    "usage_sync_interval_seconds"?: number | null;
}

export interface UsageAggregateSummary {
    "event_count": number;
    "session_count": number;
    "fresh_input_tokens": number;
    "input_tokens": number;
    "cached_input_tokens": number;
    "output_tokens": number;
    "total_tokens": number;
    "cache_hit_rate": number;
    "known_estimated_cost_usd": string;
    "cost_status": string;
    "estimated_cost_event_count": number;
    "partial_cost_event_count": number;
    "unknown_cost_event_count": number;
    "estimated_token_count": number;
    "pricing_coverage": number;
    "undated_event_count": number;
}

export interface UsageImportSummary {
    "tracked_files": number;
    "last_synced_at_unix_ms": number;
    "invalid_lines": number;
    "unsupported_lines": number;
}

export interface UsageModelSummary {
    "model": string;
    "summary": UsageAggregateSummary;
}

export interface UsagePricingInfo {
    "basis": string;
    "source_url": string;
    "verified_at": string;
    "historical_repricing": boolean;
}

export enum UsageRangePreset {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    UsageRangeToday = "today",
    UsageRange7Days = "7d",
    UsageRange30Days = "30d",
    UsageRangeAll = "all",
};

/**
 * Codex session logs do not prove which stored credential served a request;
 * reports intentionally stop at provider, model, time, and session aggregates.
 */
export interface UsageReportResult {
    "provider_id": string;
    "source": string;
    "sources": string[] | null;
    "range": UsageResolvedRange;
    "summary": UsageAggregateSummary;
    "trend": UsageTrendPoint[] | null;
    "models": UsageModelSummary[] | null;
    "import": UsageImportSummary;
    "pricing": UsagePricingInfo;
}

export interface UsageResolvedRange {
    "preset": UsageRangePreset;
    "start_unix_ms": number;
    "end_exclusive_unix_ms": number;
    "bucket_unit": string;
    "time_zone": string;
}

export interface UsageSummaryResult {
    "provider_id": string;
    "source": string;
    "sources": string[] | null;
    "event_count": number;
    "input_tokens": number;
    "cached_input_tokens": number;
    "output_tokens": number;
    "total_tokens": number;
    "estimated_cost_usd": string | null;
    "cost_status": string;
    "unknown_cost_event_count": number;
    "estimated_cost_event_count": number;
}

export interface UsageTrendPoint {
    "start_unix_ms": number;
    "end_unix_ms": number;
    "summary": UsageAggregateSummary;
}
