// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Info {
    "ProductName": string;
    "CLIName": string;
    "Version": string;
    "Commit": string;
    "BuildDate": string;
}
