// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ActiveProviderState {
    "provider_id": string;
    "provider_name": string;
    "profile_id": string;
    "profile_name": string;
    "operation_id": string;
    "updated_at_unix_ms": number;
    "profile_available": boolean;
}

export interface ApplyRollbackResult {
    "operation_id": string;
    "status": string;
    "source_operation_id": string;
    "provider_id": string;
    "profile_id": string;
    "restored_profile_id": string;
    "counts": RollbackCounts;
    "backup_path": string;
    "warnings": string[] | null;
}

export interface ApplySwitchResult {
    "operation_id": string;
    "status": string;
    "provider": PlanProvider;
    "profile": PlanProfile;
    "plan_fingerprint": string;
    "counts": SwitchCounts;
    "backup_path": string;
    "warnings": string[] | null;
}

export interface BackupDetail {
    "backup_id": string;
    "path": string;
    "operation_id": string;
    "operation_type": string;
    "operation_status": string;
    "provider_id": string;
    "profile_id": string;
    "plan_fingerprint": string;
    "created_at_unix_ms": number;
    "entry_count": number;
    "valid": boolean;
    "invalid_reason"?: string;
    "rollback_supported": boolean;
    "unsupported_reason"?: string;
    "entries": BackupEntrySummary[] | null;
}

export interface BackupEntrySummary {
    "target_id": string;
    "path": string;
    "action": string;
    "existed": boolean;
    "before_sha256": string;
    "mode"?: string;
}

export interface BackupSummary {
    "backup_id": string;
    "path": string;
    "operation_id": string;
    "operation_type": string;
    "operation_status": string;
    "provider_id": string;
    "profile_id": string;
    "plan_fingerprint": string;
    "created_at_unix_ms": number;
    "entry_count": number;
    "valid": boolean;
    "invalid_reason"?: string;
    "rollback_supported": boolean;
    "unsupported_reason"?: string;
}

export interface CodexAccount {
    "provider_id": string;
    "account_id": string;
    "secret_kind": string;
    "payload_sha256": string;
    "display_name": string;
    "metadata": { [_ in string]?: any } | null;
    "created_at_unix_ms": number;
    "updated_at_unix_ms": number;
}

export interface CodexDetectResult {
    "provider_id": string;
    "adapter_id": string;
    "codex_dir": string;
    "config_path": string;
    "auth_path": string;
    "codex_dir_exists": boolean;
    "config_status": string;
    "auth_status": string;
    "profiledeck_initialized": boolean;
    "provider_exists": boolean;
    "provider_adapter_id": string;
    "provider_compatible": boolean;
    "warnings": string[] | null;
}

export interface CodexProfileCaptureResult {
    "provider": Provider;
    "profile": Profile;
    "account": CodexAccount;
    "config_target": ProfileTarget;
    "auth_target": ProfileTarget;
    "codex_dir": string;
    "config_path": string;
    "auth_path": string;
    "warnings": string[] | null;
}

export interface CodexProfileSetResult {
    "provider": Provider;
    "profile": Profile;
    "target": ProfileTarget;
    "auth_target"?: ProfileTarget | null;
    "codex_dir": string;
    "config_path": string;
    "auth_path": string;
    "managed_keys": string[] | null;
    "warnings": string[] | null;
}

export interface DoctorFinding {
    "id": string;
    "level": string;
    "message": string;
    "details"?: { [_ in string]?: any } | null;
}

export interface DoctorLock {
    "path": string;
    "exists": boolean;
    "owner"?: string;
    "operation_id"?: string;
    "pid"?: number;
    "pid_state": string;
    "created_at_unix_ms"?: number;
    "operation_status"?: string;
    "os_lock_state": string;
    "stale_candidate": boolean;
    "repairable": boolean;
    "level": string;
    "reason": string;
}

export interface DoctorOperation {
    "id": string;
    "operation_type": string;
    "status": string;
    "checkpoint"?: string;
    "provider_id"?: string;
    "profile_id"?: string;
    "backup_path"?: string;
    "backup_id"?: string;
    "source_operation_id"?: string;
    "rollback_kind"?: string;
    "recovery_status"?: string;
    "recovery_reason"?: string;
    "error_code"?: string;
    "error_message"?: string;
    "updated_at_unix_ms": number;
    "level": string;
    "reason": string;
}

export interface DoctorRepairLockResult {
    "path": string;
    "repaired": boolean;
    "reason": string;
}

export interface DoctorResult {
    "config_dir": string;
    "runtime_root": string;
    "database_path": string;
    "overall_level": string;
    "findings": DoctorFinding[] | null;
    "operations": DoctorOperation[] | null;
    "lock": DoctorLock;
}

export interface Info {
    "ProductName": string;
    "CLIName": string;
    "Version": string;
    "Commit": string;
    "BuildDate": string;
}

export interface InitResult {
    "config_dir": string;
    "runtime_root": string;
    "database_path": string;
    "initialized": boolean;
    "schema_healthy": boolean;
    "migrations_applied": number;
}

export interface ListBackupsResult {
    "backups": BackupSummary[] | null;
}

export interface PlanOperation {
    "provider_id": string;
    "profile_id": string;
    "target_id": string;
    "path": string;
    "format": string;
    "strategy": string;
    "action": string;
    "status_reason": string;
    "file_exists": boolean;
    "is_symlink": boolean;
    "before_sha256": string;
    "desired_sha256": string;
    "before_preview": TextPreview;
    "desired_preview": TextPreview;
    "after_preview": TextPreview;
    "warnings": string[] | null;
}

export interface PlanProfile {
    "id": string;
    "name": string;
    "description": string;
}

export interface PlanProvider {
    "id": string;
    "name": string;
    "adapter_id": string;
}

export interface Profile {
    "id": string;
    "name": string;
    "description": string;
    "metadata": { [_ in string]?: any } | null;
    "created_at_unix_ms": number;
    "updated_at_unix_ms": number;
}

export interface ProfileTarget {
    "profile_id": string;
    "provider_id": string;
    "target_id": string;
    "path": string;
    "format": string;
    "strategy": string;
    "enabled": boolean;
    "value_preview": TextPreview;
    "metadata": { [_ in string]?: any } | null;
    "created_at_unix_ms": number;
    "updated_at_unix_ms": number;
}

export interface Provider {
    "id": string;
    "name": string;
    "adapter_id": string;
    "enabled": boolean;
    "metadata": { [_ in string]?: any } | null;
    "created_at_unix_ms": number;
    "updated_at_unix_ms": number;
}

export interface RecoverFailedSwitchResult {
    "operation_id": string;
    "operation_type": string;
    "rollback_kind": string;
    "status": string;
    "source_operation_id": string;
    "provider_id": string;
    "profile_id": string;
    "restored_profile_id": string;
    "counts": RollbackCounts;
    "backup_path": string;
    "warnings": string[] | null;
}

export interface RollbackCounts {
    "restore": number;
    "remove": number;
    "noop": number;
}

export interface StatusResult {
    "config_dir": string;
    "runtime_root": string;
    "database_path": string;
    "initialized": boolean;
    "schema_healthy": boolean;
    "pending_operations": number;
    "failed_operations": number;
}

export interface SwitchCounts {
    "create": number;
    "update": number;
    "noop": number;
}

export interface SwitchPlan {
    "created_at_unix_ms": number;
    "read_only": boolean;
    "plan_fingerprint": string;
    "provider": PlanProvider;
    "profile": PlanProfile;
    "operations": PlanOperation[] | null;
    "warnings": string[] | null;
}

export interface TextPreview {
    "content": string;
    "truncated": boolean;
}

export interface UsageImportError {
    "source_key": string;
    "file_name"?: string;
    "message": string;
}

export interface UsageSummaryResult {
    "provider_id": string;
    "source": string;
    "sources": string[] | null;
    "event_count": number;
    "input_tokens": number;
    "cached_input_tokens": number;
    "output_tokens": number;
    "total_tokens": number;
    "estimated_cost_usd": string | null;
    "cost_status": string;
    "unknown_cost_event_count": number;
    "estimated_cost_event_count": number;
}

export interface UsageSyncResult {
    "provider_id": string;
    "source": string;
    "scanned_files": number;
    "skipped_unchanged_files": number;
    "imported_events": number;
    "skipped_duplicate_events": number;
    "unsupported_lines": number;
    "invalid_lines": number;
    "errors": UsageImportError[] | null;
}
