// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ProfileTarget {
    "profile_id": string;
    "provider_id": string;
    "target_id": string;
    "path": string;
    "format": string;
    "strategy": string;
    "enabled": boolean;
    "value_preview": TextPreview;
    "metadata": { [_ in string]?: any } | null;
    "created_at_unix_ms": number;
    "updated_at_unix_ms": number;
}

export interface TextPreview {
    "content": string;
    "truncated": boolean;
}
