// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Desktop {
    "language": string;
    "appearance": string;
    "sidebar_collapsed": boolean;
    "automatic_updates": boolean;
    "update_channel": string;
    "automatic_backups": boolean;
}

export interface UpdateRequest {
    "language"?: string | null;
    "appearance"?: string | null;
    "sidebar_collapsed"?: boolean | null;
}
