// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Status {
    "automatic": boolean;
    "catalog_version": number;
    "last_checked_at_unix_ms": number;
    "last_updated_at_unix_ms": number;
    "last_error"?: string;
}
