// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ActiveState {
    "provider_id": string;
    "provider_name": string;
    "profile_id": string;
    "profile_name": string;
    "revision": number;
    "updated_at_unix_ms": number;
    "profile_available": boolean;
}

export interface Provider {
    "id": string;
    "name": string;
    "adapter_id": string;
    "metadata": { [_ in string]?: any } | null;
    "created_at_unix_ms": number;
    "updated_at_unix_ms": number;
}
