// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profile$0 from "../profile/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "../provider/models.js";

export interface CodexConfigSet {
    "id": string;
    "name": string;
    "description"?: string;
    "reference_count": number;
    "active": boolean;
    "model"?: string;
    "model_provider"?: string;
    "openai_base_url"?: string;
    "payload_sha256": string;
    "created_at_unix_ms": number;
    "updated_at_unix_ms": number;
}

export interface CodexConfigSetListResult {
    "config_sets": CodexConfigSet[] | null;
}

export interface CodexDetectResult {
    "provider_id": string;
    "adapter_id": string;
    "codex_dir": string;
    "config_path": string;
    "auth_path": string;
    "codex_dir_exists": boolean;
    "config_status": string;
    "auth_status": string;
    "profiledeck_initialized": boolean;
    "provider_exists": boolean;
    "provider_adapter_id": string;
    "provider_compatible": boolean;
    "warnings": string[] | null;
}

export interface CodexLoginStateSummary {
    "credential_id": string;
    "codex_account_id"?: string;
    "reference_count": number;
    "updated_at_unix_ms": number;
}

export interface CodexProfileDetail {
    "summary": CodexProfileSummary;
    "login"?: CodexLoginStateSummary | null;
    "config_set"?: CodexConfigSet | null;
}

export interface CodexProfileExportResult {
    "path": string;
    "sha256": string;
    "file_mode": string;
    "profile_count": number;
    "credential_count": number;
    "config_set_count": number;
    "warnings": string[] | null;
}

export interface CodexProfileImportCounts {
    "create": number;
    "unchanged": number;
    "conflict": number;
}

export interface CodexProfileImportItem {
    "kind": string;
    "id": string;
    "name"?: string;
    "credential_id"?: string;
    "config_set_id"?: string;
    "action": string;
    "reason"?: string;
}

export interface CodexProfileImportPlan {
    "path": string;
    "file_sha256": string;
    "plan_fingerprint": string;
    "codex_dir": string;
    "can_apply": boolean;
    "no_changes": boolean;
    "counts": CodexProfileImportCounts;
    "items": CodexProfileImportItem[] | null;
    "profile_count": number;
    "credential_count": number;
    "config_set_count": number;
    "warnings": string[] | null;
}

export interface CodexProfileImportResult {
    "operation_id"?: string;
    "file_sha256": string;
    "plan_fingerprint": string;
    "changed": boolean;
    "counts": CodexProfileImportCounts;
    "profile_count": number;
    "credential_count": number;
    "config_set_count": number;
    "warnings": string[] | null;
}

export interface CodexProfileListResult {
    "profiles": CodexProfileSummary[] | null;
}

export interface CodexProfileQuota {
    "profile_id": string;
    "credential_id"?: string;
    "status": CodexProfileQuotaStatus;
    "snapshot"?: CodexQuotaSnapshot | null;
}

export enum CodexProfileQuotaStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CodexProfileQuotaAvailable = "available",
    CodexProfileQuotaAuthRequired = "auth_required",
    CodexProfileQuotaUnsupported = "unsupported",
    CodexProfileQuotaUnavailable = "unavailable",
};

export interface CodexProfileSaveResult {
    "operation_id": string;
    "provider": provider$0.Provider;
    "profile": profile$0.Profile;
    "summary": CodexProfileSummary;
    "config_set": CodexConfigSet;
    "codex_dir": string;
    "config_path": string;
    "auth_path": string;
    "warnings"?: string[] | null;
}

export interface CodexProfileSettings {
    "profile_id": string;
    "profile_name": string;
    "credential_reference_count": number;
    "quota_refresh_interval_seconds": number;
    "auth_keepalive_enabled": boolean;
    "auth_mode": string;
    "quota_supported": boolean;
    "auth_keepalive_supported": boolean;
    "updated_at_unix_ms": number;
}

export interface CodexProfileStateSaveResult {
    "operation_id": string;
    "profile_id": string;
    "credential_id": string;
    "credential_reference_count": number;
    "config_set": CodexConfigSet;
    "warnings"?: string[] | null;
}

export interface CodexProfileSummary {
    "profile": profile$0.Profile;
    "provider_id": string;
    "credential_id"?: string;
    "credential_reference_count": number;
    "codex_account_id"?: string;
    "config_set_id"?: string;
    "config_set_name"?: string;
    "config_set_reference_count": number;
    "model"?: string;
    "model_provider"?: string;
    "openai_base_url"?: string;
    "active": boolean;
    "updated_at_unix_ms": number;
    "warnings"?: string[] | null;
}

export interface CodexQuotaCredits {
    "has_credits": boolean;
    "unlimited": boolean;
    "balance"?: string | null;
}

export interface CodexQuotaRateLimit {
    "id": string;
    "name"?: string;
    "allowed": boolean;
    "limit_reached": boolean;
    "primary_window"?: CodexQuotaWindow | null;
    "secondary_window"?: CodexQuotaWindow | null;
}

export interface CodexQuotaSnapshot {
    "fetched_at_unix_ms": number;
    "plan_type"?: string;
    "rate_limit"?: CodexQuotaRateLimit | null;
    "additional_rate_limits": CodexQuotaRateLimit[] | null;
    "credits"?: CodexQuotaCredits | null;
    "spend_control"?: CodexQuotaSpendControl | null;
    "rate_limit_reached_type"?: string;
    "reset_credits_available_count"?: number | null;
}

export interface CodexQuotaSpendControl {
    "reached": boolean;
    "individual_limit"?: CodexQuotaSpendControlLimit | null;
}

export interface CodexQuotaSpendControlLimit {
    "source"?: string;
    "limit": string;
    "used": string;
    "remaining": string;
    "used_percent": number;
    "remaining_percent": number;
    "reset_after_seconds": number;
    "reset_at_unix_seconds": number;
}

export interface CodexQuotaWindow {
    "used_percent": number;
    "remaining_percent": number;
    "limit_window_seconds": number;
    "reset_after_seconds": number;
    "reset_at_unix_seconds": number;
}

export interface CodexSettings {
    "usage_sync_interval_seconds": number;
    "profiles": CodexProfileSettings[] | null;
}

export interface UpdateCodexSettingsRequest {
    "profile_id"?: string;
    "usage_sync_interval_seconds"?: number | null;
    "quota_refresh_interval_seconds"?: number | null;
    "auth_keepalive_enabled"?: boolean | null;
}
