// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profile$0 from "../profile/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "../provider/models.js";

/**
 * ConfigSet intentionally contains no configuration body or content-derived
 * fingerprint because Grok Build settings are sensitive at every output boundary.
 */
export interface ConfigSet {
    "id": string;
    "name": string;
    "description"?: string;
    "reference_count": number;
    "active": boolean;
    "created_at_unix_ms": number;
    "updated_at_unix_ms": number;
}

export interface ConfigSetListResult {
    "config_sets": ConfigSet[] | null;
}

export interface DetectResult {
    "provider_id": string;
    "adapter_id": string;
    "grok_home": string;
    "config_path": string;
    "auth_path": string;
    "grok_home_exists": boolean;
    "config_status": string;
    "auth_status": string;
    "file_auth_supported": boolean;
    "profiledeck_initialized": boolean;
    "provider_exists": boolean;
    "provider_adapter_id"?: string;
    "provider_compatible": boolean;
    "warnings"?: string[] | null;
}

export interface LoginSummary {
    "credential_id": string;
    "reference_count": number;
    "updated_at_unix_ms": number;
}

export interface ProfileDetail {
    "summary": ProfileSummary;
    "login"?: LoginSummary | null;
    "config_set"?: ConfigSet | null;
}

export interface ProfileListResult {
    "profiles": ProfileSummary[] | null;
}

export interface ProfileSaveResult {
    "operation_id": string;
    "provider": provider$0.Provider;
    "profile": profile$0.Profile;
    "summary": ProfileSummary;
    "config_set": ConfigSet;
    "grok_home": string;
    "config_path": string;
    "auth_path": string;
    "warnings"?: string[] | null;
}

export interface ProfileStateSaveResult {
    "operation_id": string;
    "profile_id": string;
    "credential_id": string;
    "credential_reference_count": number;
    "config_set": ConfigSet;
    "warnings"?: string[] | null;
}

export interface ProfileSummary {
    "profile": profile$0.Profile;
    "provider_id": string;
    "credential_id"?: string;
    "credential_reference_count": number;
    "config_set_id"?: string;
    "config_set_name"?: string;
    "config_set_reference_count": number;
    "active": boolean;
    "updated_at_unix_ms": number;
    "warnings"?: string[] | null;
}

export interface Settings {
    "usage_sync_interval_seconds": number;
}

export interface UpdateSettingsRequest {
    "usage_sync_interval_seconds"?: number | null;
}
