// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    DoctorLock,
    DoctorOperation,
    DoctorRepairLockResult,
    DoctorResult,
    Finding
} from "./models.js";
