// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DoctorLock {
    "path": string;
    "exists": boolean;
    "owner"?: string;
    "operation_id"?: string;
    "pid"?: number;
    "pid_state": string;
    "created_at_unix_ms"?: number;
    "operation_status"?: string;
    "os_lock_state": string;
    "stale_candidate": boolean;
    "repairable": boolean;
    "level": string;
    "reason": string;
}

export interface DoctorOperation {
    "id": string;
    "operation_type": string;
    "status": string;
    "checkpoint"?: string;
    "provider_id"?: string;
    "profile_id"?: string;
    "recovery_status"?: string;
    "recovery_action"?: string;
    "recovery_reason"?: string;
    "error_code"?: string;
    "error_message"?: string;
    "updated_at_unix_ms": number;
    "level": string;
    "reason": string;
}

export interface DoctorRepairLockResult {
    "path": string;
    "repaired": boolean;
    "reason": string;
}

export interface DoctorResult {
    "config_dir": string;
    "runtime_root": string;
    "database_path": string;
    "overall_level": string;
    "findings": Finding[] | null;
    "operations": DoctorOperation[] | null;
    "lock": DoctorLock;
}

/**
 * Finding is a structured diagnostic result shared by all entrypoints.
 */
export interface Finding {
    "id": string;
    "level": string;
    "message": string;
    "details"?: { [_ in string]?: any } | null;
}
