// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface UpdateStatus {
    "configured": boolean;
    "automatic": boolean;
    "state": string;
    "current_version": string;
    "available_version": string;
    "downloaded_bytes": number;
    "total_bytes": number;
    "last_checked_at_unix_ms": number;
    "error_code": string;
}
