// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckAndDownload(): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(7532155);
}

export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(2161813081);
}

export function SetAutomatic(enabled: boolean): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(2063367537, enabled);
}

export function SetChannel(channel: string): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(2103121129, channel);
}

export function Status(): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(2583455528);
}
